// js/celestialBodies.js

/*
============================================================
UNIVERSE EXPLORER
CELESTIAL BODIES DATABASE
============================================================

Main database for:
- Stars
- Sun
- Planets
- Dwarf planets
- Moons
- Important small bodies

Graphics are generated by app.js.
This file contains only structured astronomical data.
============================================================
*/


/* =========================================================
   HELPER
========================================================= */

function createBody(data) {
    return {
        name: data.name,
        type: data.type,

        position: data.position || [0, 0, 0],

        radius: data.radius || 1,
        color: data.color || 0xffffff,

        size: data.size || "Unknown",
        mass: data.mass || "Unknown",
        temperature: data.temperature || "Unknown",
        gravity: data.gravity || "Unknown",

        composition: data.composition || "Unknown",
        atmosphere: data.atmosphere || "None",

        rotation: data.rotation || "Unknown",
        orbit: data.orbit || "Unknown",

        textureStyle: data.textureStyle || "rocky",

        atmosphereColor:
            data.atmosphereColor || data.color || 0xffffff,

        hasAtmosphere:
            data.hasAtmosphere || false,

        hasRings:
            data.hasRings || false,

        parent:
            data.parent || null,

        facts:
            data.facts || []
    };
}


/* =========================================================
   SUN
========================================================= */

export const Sun = createBody({

    name: "Sun",
    type: "Star",

    position: [0, 0, 0],

    radius: 3.5,
    color: 0xffb52e,

    size: "1,392,700 km",
    mass: "1.989 × 10³⁰ kg",

    temperature:
        "5,500°C surface / ~15 million°C core",

    gravity: "274 m/s²",

    composition:
        "Hydrogen and helium",

    atmosphere:
        "Extremely hot plasma",

    rotation:
        "25–35 days",

    orbit:
        "Around the center of the Milky Way",

    textureStyle: "sun",

    atmosphereColor: 0xff7b18,

    hasAtmosphere: true,

    facts: [
        "The Sun is the star at the center of our Solar System.",
        "It contains about 99.8% of the mass of the Solar System.",
        "Energy is produced through nuclear fusion.",
        "The Sun produces solar wind and powerful solar eruptions."
    ]
});


/* =========================================================
   PLANETS
========================================================= */

export const Mercury = createBody({

    name: "Mercury",
    type: "Planet",

    position: [7, 0, 0],

    radius: 0.45,
    color: 0x91877c,

    size: "4,879 km",
    mass: "3.301 × 10²³ kg",

    temperature:
        "-180°C to 430°C",

    gravity: "3.70 m/s²",

    composition:
        "Rock and iron",

    atmosphere:
        "Extremely thin exosphere",

    rotation:
        "58.6 Earth days",

    orbit:
        "87.97 Earth days",

    textureStyle: "cratered",

    facts: [
        "Mercury is the smallest planet.",
        "It has a very large iron core.",
        "Its surface is heavily cratered.",
        "Mercury has almost no atmosphere."
    ]
});


export const Venus = createBody({

    name: "Venus",
    type: "Planet",

    position: [11, 0, 0],

    radius: 0.85,
    color: 0xd7b875,

    size: "12,104 km",
    mass: "4.867 × 10²⁴ kg",

    temperature:
        "Approximately 465°C",

    gravity: "8.87 m/s²",

    composition:
        "Rock and metal",

    atmosphere:
        "Dense carbon dioxide and nitrogen",

    rotation:
        "243 Earth days",

    orbit:
        "224.7 Earth days",

    textureStyle: "venus",

    atmosphereColor: 0xf0c982,

    hasAtmosphere: true,

    facts: [
        "Venus is the hottest planet.",
        "Its atmosphere is dominated by carbon dioxide.",
        "Its clouds contain sulfuric acid.",
        "Venus rotates in the opposite direction to most planets."
    ]
});


export const Earth = createBody({

    name: "Earth",
    type: "Planet",

    position: [15, 0, 0],

    radius: 1,
    color: 0x2f78d1,

    size: "12,742 km",
    mass: "5.972 × 10²⁴ kg",

    temperature:
        "Approximately 15°C average",

    gravity: "9.81 m/s²",

    composition:
        "Iron, oxygen, silicon, magnesium and other elements",

    atmosphere:
        "78% nitrogen, 21% oxygen",

    rotation:
        "23h 56m",

    orbit:
        "365.25 days",

    textureStyle: "earth",

    atmosphereColor: 0x4da6ff,

    hasAtmosphere: true,

    facts: [
        "Earth is the only known world with life.",
        "About 71% of its surface is covered by oceans.",
        "Earth has a protective magnetic field.",
        "Liquid water exists naturally on its surface."
    ]
});


export const Mars = createBody({

    name: "Mars",
    type: "Planet",

    position: [20, 0, 0],

    radius: 0.53,
    color: 0xb34c32,

    size: "6,779 km",
    mass: "6.417 × 10²³ kg",

    temperature:
        "Approximately -63°C average",

    gravity: "3.71 m/s²",

    composition:
        "Rock and iron",

    atmosphere:
        "Thin carbon dioxide atmosphere",

    rotation:
        "24h 37m",

    orbit:
        "687 Earth days",

    textureStyle: "mars",

    atmosphereColor: 0xb95b45,

    hasAtmosphere: true,

    facts: [
        "Mars is known as the Red Planet.",
        "Its surface contains iron oxide.",
        "Olympus Mons is the largest volcano in the Solar System.",
        "Mars has two small moons."
    ]
});


export const Jupiter = createBody({

    name: "Jupiter",
    type: "Planet",

    position: [29, 0, 0],

    radius: 2.25,
    color: 0xc9956b,

    size: "139,820 km",
    mass: "1.898 × 10²⁷ kg",

    temperature:
        "Approximately -110°C cloud tops",

    gravity: "24.79 m/s²",

    composition:
        "Hydrogen and helium",

    atmosphere:
        "Hydrogen, helium and trace compounds",

    rotation:
        "9h 56m",

    orbit:
        "11.86 Earth years",

    textureStyle: "gasGiant",

    atmosphereColor: 0xd7b58c,

    hasAtmosphere: true,

    facts: [
        "Jupiter is the largest planet.",
        "It has a powerful magnetic field.",
        "The Great Red Spot is a gigantic storm.",
        "Jupiter has dozens of known moons."
    ]
});


export const Saturn = createBody({

    name: "Saturn",
    type: "Planet",

    position: [39, 0, 0],

    radius: 1.9,
    color: 0xd6bd88,

    size: "116,460 km",
    mass: "5.683 × 10²⁶ kg",

    temperature:
        "Approximately -140°C cloud tops",

    gravity: "10.44 m/s²",

    composition:
        "Hydrogen and helium",

    atmosphere:
        "Hydrogen and helium",

    rotation:
        "Approximately 10.7 hours",

    orbit:
        "29.45 Earth years",

    textureStyle: "saturn",

    atmosphereColor: 0xe4cf9c,

    hasAtmosphere: true,
    hasRings: true,

    facts: [
        "Saturn has the most spectacular visible ring system.",
        "Its rings are mostly ice particles.",
        "Saturn is less dense than water.",
        "Titan is its largest moon."
    ]
});


export const Uranus = createBody({

    name: "Uranus",
    type: "Planet",

    position: [51, 0, 0],

    radius: 1.55,
    color: 0x8edce5,

    size: "50,724 km",
    mass: "8.681 × 10²⁵ kg",

    temperature:
        "Approximately -195°C",

    gravity: "8.69 m/s²",

    composition:
        "Water, methane and ammonia ices",

    atmosphere:
        "Hydrogen, helium and methane",

    rotation:
        "Approximately 17 hours",

    orbit:
        "84 Earth years",

    textureStyle: "iceGiant",

    atmosphereColor: 0x8ee9ef,

    hasAtmosphere: true,
    hasRings: true,

    facts: [
        "Uranus rotates almost on its side.",
        "Methane gives it a blue-green appearance.",
        "Uranus has a faint ring system.",
        "It has 27 known moons."
    ]
});


export const Neptune = createBody({

    name: "Neptune",
    type: "Planet",

    position: [64, 0, 0],

    radius: 1.5,
    color: 0x315bd8,

    size: "49,244 km",
    mass: "1.024 × 10²⁶ kg",

    temperature:
        "Approximately -200°C",

    gravity: "11.15 m/s²",

    composition:
        "Water, ammonia and methane ices",

    atmosphere:
        "Hydrogen, helium and methane",

    rotation:
        "Approximately 16 hours",

    orbit:
        "164.8 Earth years",

    textureStyle: "neptune",

    atmosphereColor: 0x4775e8,

    hasAtmosphere: true,

    facts: [
        "Neptune is the most distant major planet.",
        "It has extremely powerful winds.",
        "Methane contributes to its blue color.",
        "Neptune has a faint ring system."
    ]
});


/* =========================================================
   DWARF PLANETS
========================================================= */

export const Pluto = createBody({

    name: "Pluto",
    type: "Dwarf Planet",

    position: [82, 0, 0],

    radius: 0.30,
    color: 0xb9a997,

    size: "2,377 km",
    mass: "1.303 × 10²² kg",

    temperature:
        "Approximately -230°C",

    gravity: "0.62 m/s²",

    composition:
        "Rock and ice",

    atmosphere:
        "Thin nitrogen atmosphere",

    rotation:
        "6.39 Earth days",

    orbit:
        "248 Earth years",

    textureStyle: "pluto",

    atmosphereColor: 0xc8b6a1,

    hasAtmosphere: true,

    facts: [
        "Pluto is a dwarf planet in the Kuiper Belt.",
        "It has a large heart-shaped region.",
        "Charon is its largest moon.",
        "Pluto has a complex icy surface."
    ]
});


export const Ceres = createBody({

    name: "Ceres",
    type: "Dwarf Planet",

    position: [25, 0, 0],

    radius: 0.20,
    color: 0x8f8982,

    size: "939 km",
    mass: "9.383 × 10²⁰ kg",

    temperature:
        "Approximately -105°C",

    gravity: "0.27 m/s²",

    composition:
        "Rock and ice",

    atmosphere:
        "Extremely thin exosphere",

    rotation:
        "9 hours",

    orbit:
        "4.6 Earth years",

    textureStyle: "dwarfRocky",

    facts: [
        "Ceres is the largest object in the asteroid belt.",
        "It is classified as a dwarf planet.",
        "Bright deposits of salts have been observed on its surface."
    ]
});


export const Eris = createBody({

    name: "Eris",
    type: "Dwarf Planet",

    position: [105, 0, -20],

    radius: 0.31,
    color: 0xd5d7dc,

    size: "2,326 km",
    mass: "1.646 × 10²² kg",

    temperature:
        "Extremely cold",

    gravity: "0.82 m/s²",

    composition:
        "Rock and ice",

    atmosphere:
        "Very thin / seasonal",

    rotation:
        "25.9 hours",

    orbit:
        "Approximately 558 years",

    textureStyle: "icyDwarf",

    facts: [
        "Eris is one of the largest known dwarf planets.",
        "It helped trigger the modern debate over Pluto's classification.",
        "Eris has a moon called Dysnomia."
    ]
});


export const Haumea = createBody({

    name: "Haumea",
    type: "Dwarf Planet",

    position: [112, 30, -35],

    radius: 0.24,
    color: 0xd9e0e5,

    size: "Approximately 1,560 km",

    mass: "4.006 × 10²¹ kg",

    temperature:
        "Extremely cold",

    gravity:
        "Very weak",

    composition:
        "Rock and water ice",

    atmosphere:
        "None known",

    rotation:
        "Approximately 3.9 hours",

    orbit:
        "Approximately 284 years",

    textureStyle: "icyDwarf",

    hasRings: true,

    facts: [
        "Haumea has an unusual elongated shape.",
        "It rotates extremely quickly.",
        "It has two known moons.",
        "A faint ring system surrounds Haumea."
    ]
});


export const Makemake = createBody({

    name: "Makemake",
    type: "Dwarf Planet",

    position: [118, -25, -40],

    radius: 0.23,
    color: 0xc8c0b8,

    size: "Approximately 1,430 km",

    mass: "Approximately 3.1 × 10²¹ kg",

    temperature:
        "Extremely cold",

    gravity:
        "Very weak",

    composition:
        "Rock and volatile ices",

    atmosphere:
        "Very thin / seasonal",

    rotation:
        "Approximately 22.8 hours",

    orbit:
        "Approximately 305 years",

    textureStyle: "icyDwarf",

    facts: [
        "Makemake is a dwarf planet in the Kuiper Belt.",
        "Its surface contains frozen volatile materials.",
        "It has a small known moon."
    ]
});


/* =========================================================
   MOON — EARTH
========================================================= */

export const Moon = createBody({

    name: "Moon",
    type: "Moon",

    position: [16.8, 0, 0],

    radius: 0.27,
    color: 0xb7b7b7,

    size: "3,475 km",
    mass: "7.342 × 10²² kg",

    temperature:
        "-173°C to 127°C",

    gravity: "1.62 m/s²",

    composition:
        "Rock and minerals",

    atmosphere:
        "Extremely thin exosphere",

    rotation:
        "27.3 Earth days",

    orbit:
        "27.3 Earth days around Earth",

    textureStyle: "moon",

    parent: "Earth",

    facts: [
        "The Moon is Earth's natural satellite.",
        "It is tidally locked to Earth.",
        "Its surface contains many impact craters.",
        "The Moon influences Earth's tides."
    ]
});


/* =========================================================
   JUPITER MOONS
========================================================= */

export const Io = createBody({

    name: "Io",
    type: "Moon",

    position: [32, 0, 0],

    radius: 0.29,
    color: 0xd8b52d,

    size: "3,643 km",
    mass: "8.93 × 10²² kg",

    temperature:
        "Variable",

    gravity: "1.80 m/s²",

    composition:
        "Silicate rock and sulfur",

    atmosphere:
        "Very thin sulfur dioxide atmosphere",

    rotation:
        "1.77 days",

    orbit:
        "1.77 days around Jupiter",

    textureStyle: "volcanic",

    hasAtmosphere: true,
    atmosphereColor: 0xd8a830,

    parent: "Jupiter",

    facts: [
        "Io is the most volcanically active world known.",
        "Its surface is covered by sulfur-rich deposits.",
        "Jupiter's gravity creates enormous tidal forces."
    ]
});


export const Europa = createBody({

    name: "Europa",
    type: "Moon",

    position: [33, 0, 0],

    radius: 0.25,
    color: 0xcbbfa8,

    size: "3,122 km",
    mass: "4.80 × 10²² kg",

    temperature:
        "Extremely cold",

    gravity: "1.31 m/s²",

    composition:
        "Water ice and rock",

    atmosphere:
        "Very thin oxygen atmosphere",

    rotation:
        "3.55 days",

    orbit:
        "3.55 days around Jupiter",

    textureStyle: "icyMoon",

    hasAtmosphere: true,
    atmosphereColor: 0xccecff,

    parent: "Jupiter",

    facts: [
        "Europa has a thick shell of water ice.",
        "A subsurface ocean may exist beneath its surface.",
        "Europa is one of the most interesting targets for future exploration."
    ]
});


export const Ganymede = createBody({

    name: "Ganymede",
    type: "Moon",

    position: [35, 0, 0],

    radius: 0.42,
    color: 0x9e9a91,

    size: "5,268 km",
    mass: "1.482 × 10²³ kg",

    temperature:
        "Extremely cold",

    gravity: "1.43 m/s²",

    composition:
        "Rock and water ice",

    atmosphere:
        "Very thin oxygen environment",

    rotation:
        "7.15 days",

    orbit:
        "7.15 days around Jupiter",

    textureStyle: "icyRocky",

    hasAtmosphere: true,
    atmosphereColor: 0xbfdfff,

    parent: "Jupiter",

    facts: [
        "Ganymede is the largest moon in the Solar System.",
        "It is larger than Mercury.",
        "Ganymede has its own magnetic field."
    ]
});


export const Callisto = createBody({

    name: "Callisto",
    type: "Moon",

    position: [37, 0, 0],

    radius: 0.38,
    color: 0x77736e,

    size: "4,821 km",
    mass: "1.076 × 10²³ kg",

    temperature:
        "Approximately -139°C",

    gravity: "1.24 m/s²",

    composition:
        "Rock and ice",

    atmosphere:
        "Very thin carbon dioxide environment",

    rotation:
        "16.7 days",

    orbit:
        "16.7 days around Jupiter",

    textureStyle: "cratered",

    hasAtmosphere: true,
    atmosphereColor: 0x9ba4ae,

    parent: "Jupiter",

    facts: [
        "Callisto is heavily cratered.",
        "It is the second-largest moon of Jupiter.",
        "Its surface is one of the oldest in the Solar System."
    ]
});


/* =========================================================
   SATURN MOONS
========================================================= */

export const Titan = createBody({

    name: "Titan",
    type: "Moon",

    position: [42, 0, 0],

    radius: 0.40,
    color: 0xd69b52,

    size: "5,150 km",
    mass: "1.345 × 10²³ kg",

    temperature:
        "Approximately -179°C",

    gravity: "1.35 m/s²",

    composition:
        "Rock and ice",

    atmosphere:
        "Dense nitrogen atmosphere with methane",

    rotation:
        "15.9 days",

    orbit:
        "15.9 days around Saturn",

    textureStyle: "titan",

    atmosphereColor: 0xd58b3c,

    hasAtmosphere: true,

    parent: "Saturn",

    facts: [
        "Titan is Saturn's largest moon.",
        "It has a thick atmosphere.",
        "Titan has lakes and seas of liquid hydrocarbons.",
        "Titan is one of the most Earth-like moons."
    ]
});


export const Rhea = createBody({

    name: "Rhea",
    type: "Moon",

    position: [43.5, 0, 0],

    radius: 0.22,
    color: 0xbebebe,

    size: "1,528 km",
    mass: "2.307 × 10²¹ kg",

    temperature:
        "Extremely cold",

    gravity: "0.264 m/s²",

    composition:
        "Water ice and rock",

    atmosphere:
        "Very thin exosphere",

    rotation:
        "4.52 days",

    orbit:
        "4.52 days around Saturn",

    textureStyle: "icyMoon",

    parent: "Saturn",

    facts: [
        "Rhea is Saturn's second-largest moon.",
        "Its surface is heavily cratered.",
        "Rhea contains large amounts of water ice."
    ]
});


export const Enceladus = createBody({

    name: "Enceladus",
    type: "Moon",

    position: [41.5, 0, 0],

    radius: 0.16,
    color: 0xe5edf2,

    size: "504 km",
    mass: "1.08 × 10²⁰ kg",

    temperature:
        "Very cold",

    gravity: "0.113 m/s²",

    composition:
        "Water ice and rocky material",

    atmosphere:
        "Water vapor and very thin gases",

    rotation:
        "1.37 days",

    orbit:
        "1.37 days around Saturn",

    textureStyle: "icyMoon",

    atmosphereColor: 0xd9f5ff,

    hasAtmosphere: true,

    parent: "Saturn",

    facts: [
        "Enceladus has a bright icy surface.",
        "Water-rich plumes erupt from its south pole.",
        "A subsurface ocean is believed to exist beneath its ice."
    ]
});


export const Mimas = createBody({

    name: "Mimas",
    type: "Moon",

    position: [41, 0, 0],

    radius: 0.10,
    color: 0xb7b7b4,

    size: "396 km",
    mass: "3.75 × 10¹⁹ kg",

    temperature:
        "Extremely cold",

    gravity: "0.064 m/s²",

    composition:
        "Mostly water ice",

    atmosphere:
        "None",

    rotation:
        "0.94 days",

    orbit:
        "0.94 days around Saturn",

    textureStyle: "cratered",

    parent: "Saturn",

    facts: [
        "Mimas is famous for the enormous Herschel crater.",
        "Its appearance resembles a science-fiction space station in some views."
    ]
});


export const Iapetus = createBody({

    name: "Iapetus",
    type: "Moon",

    position: [46, 0, 0],

    radius: 0.21,
    color: 0x77736b,

    size: "1,469 km",
    mass: "1.806 × 10²¹ kg",

    temperature:
        "Extremely cold",

    gravity: "0.223 m/s²",

    composition:
        "Water ice and dark material",

    atmosphere:
        "None",

    rotation:
        "79.3 days",

    orbit:
        "79.3 days around Saturn",

    textureStyle: "darkIcy",

    parent: "Saturn",

    facts: [
        "Iapetus has a dramatic difference in brightness between its hemispheres.",
        "A huge equatorial ridge crosses part of the moon."
    ]
});


/* =========================================================
   URANUS MOONS
========================================================= */

export const Miranda = createBody({

    name: "Miranda",
    type: "Moon",

    position: [54, 0, 0],

    radius: 0.12,
    color: 0xa8aaa8,

    size: "472 km",
    mass: "6.59 × 10¹⁹ kg",

    temperature:
        "Extremely cold",

    gravity: "0.079 m/s²",

    composition:
        "Ice and rock",

    atmosphere:
        "None",

    rotation:
        "1.41 days",

    orbit:
        "1.41 days around Uranus",

    textureStyle: "icyRocky",

    parent: "Uranus",

    facts: [
        "Miranda has one of the strangest surfaces in the Solar System.",
        "It contains enormous cliffs and complex geological regions."
    ]
});


export const Ariel = createBody({

    name: "Ariel",
    type: "Moon",

    position: [55, 0, 0],

    radius: 0.18,
    color: 0xc0c2bd,

    size: "1,158 km",
    mass: "1.35 × 10²¹ kg",

    temperature:
        "Extremely cold",

    gravity: "0.27 m/s²",

    composition:
        "Water ice and rock",

    atmosphere:
        "None known",

    rotation:
        "2.52 days",

    orbit:
        "2.52 days around Uranus",

    textureStyle: "icyMoon",

    parent: "Uranus",

    facts: [
        "Ariel is one of Uranus's major moons.",
        "Its surface contains valleys and fractures."
    ]
});


export const Titania = createBody({

    name: "Titania",
    type: "Moon",

    position: [56, 0, 0],

    radius: 0.23,
    color: 0xaaa9a4,

    size: "1,578 km",
    mass: "3.42 × 10²¹ kg",

    temperature:
        "Extremely cold",

    gravity: "0.379 m/s²",

    composition:
        "Water ice and rock",

    atmosphere:
        "None known",

    rotation:
        "8.7 days",

    orbit:
        "8.7 days around Uranus",

    textureStyle: "icyRocky",

    parent: "Uranus",

    facts: [
        "Titania is Uranus's largest moon.",
        "Its surface contains large valleys and impact craters."
    ]
});


export const Oberon = createBody({

    name: "Oberon",
    type: "Moon",

    position: [57, 0, 0],

    radius: 0.23,
    color: 0x777772,

    size: "1,523 km",
    mass: "3.01 × 10²¹ kg",

    temperature:
        "Extremely cold",

    gravity: "0.346 m/s²",

    composition:
        "Ice and rock",

    atmosphere:
        "None known",

    rotation:
        "13.5 days",

    orbit:
        "13.5 days around Uranus",

    textureStyle: "cratered",

    parent: "Uranus",

    facts: [
        "Oberon is the outermost major moon of Uranus.",
        "Its surface contains many impact craters."
    ]
});


/* =========================================================
   NEPTUNE MOONS
========================================================= */

export const Triton = createBody({

    name: "Triton",
    type: "Moon",

    position: [67, 0, 0],

    radius: 0.39,
    color: 0xc8d1ce,

    size: "2,710 km",
    mass: "2.14 × 10²² kg",

    temperature:
        "Approximately -235°C",

    gravity: "0.779 m/s²",

    composition:
        "Water ice and nitrogen-rich ices",

    atmosphere:
        "Thin nitrogen atmosphere",

    rotation:
        "5.88 days",

    orbit:
        "5.88 days around Neptune",

    textureStyle: "icyMoon",

    atmosphereColor: 0xcceeff,

    hasAtmosphere: true,

    parent: "Neptune",

    facts: [
        "Triton is Neptune's largest moon.",
        "It has a retrograde orbit.",
        "Triton has nitrogen geysers and an extremely cold surface."
    ]
});


export const Nereid = createBody({

    name: "Nereid",
    type: "Moon",

    position: [69, 0, 0],

    radius: 0.10,
    color: 0xa5a5a2,

    size: "340 km",
    mass: "3.0 × 10¹⁹ kg",

    temperature:
        "Extremely cold",

    gravity:
        "Very weak",

    composition:
        "Rock and ice",

    atmosphere:
        "None known",

    rotation:
        "Variable",

    orbit:
        "Highly eccentric orbit around Neptune",

    textureStyle: "rockyMoon",

    parent: "Neptune",

    facts: [
        "Nereid has one of the most eccentric moon orbits known."
    ]
});


/* =========================================================
   MARS MOONS
========================================================= */

export const Phobos = createBody({

    name: "Phobos",
    type: "Moon",

    position: [21.2, 0, 0],

    radius: 0.11,
    color: 0x766b62,

    size: "27 × 22 × 18 km",
    mass: "1.0659 × 10¹⁶ kg",

    temperature:
        "Extremely variable",

    gravity:
        "Very weak",

    composition:
        "Rocky material",

    atmosphere:
        "None",

    rotation:
        "7h 39m",

    orbit:
        "7h 39m around Mars",

    textureStyle: "asteroidMoon",

    parent: "Mars",

    facts: [
        "Phobos is the larger moon of Mars.",
        "It orbits extremely close to Mars.",
        "Its surface is covered with impact craters."
    ]
});


export const Deimos = createBody({

    name: "Deimos",
    type: "Moon",

    position: [20.8, 0, 0],

    radius: 0.08,
    color: 0x8b8077,

    size: "15 × 12 × 11 km",
    mass: "1.476 × 10¹⁵ kg",

    temperature:
        "Extremely variable",

    gravity:
        "Very weak",

    composition:
        "Rocky material",

    atmosphere:
        "None",

    rotation:
        "30.3 hours",

    orbit:
        "30.3 hours around Mars",

    textureStyle: "asteroidMoon",

    parent: "Mars",

    facts: [
        "Deimos is the smaller moon of Mars.",
        "Its surface is covered with regolith and craters."
    ]
});


/* =========================================================
   IMPORTANT STARS
========================================================= */

export const Sirius = createBody({

    name: "Sirius",
    type: "Star",

    position: [-160, 60, -100],

    radius: 4,
    color: 0xbfdcff,

    size: "Approximately 2.4 million km",

    mass:
        "Approximately 4.0 × 10³⁰ kg",

    temperature:
        "Approximately 9,900°C",

    gravity:
        "Strong stellar gravity",

    composition:
        "Hydrogen and helium",

    atmosphere:
        "Stellar plasma",

    rotation:
        "Variable",

    orbit:
        "Binary star system",

    textureStyle: "star",

    atmosphereColor: 0xb8d9ff,

    hasAtmosphere: true,

    facts: [
        "Sirius is the brightest star in Earth's night sky.",
        "It is a binary star system.",
        "Sirius A is a white main-sequence star.",
        "Sirius B is a white dwarf."
    ]
});


export const AlphaCentauri = createBody({

    name: "Alpha Centauri",
    type: "Star",

    position: [-230, -30, -180],

    radius: 3.5,
    color: 0xffd27a,

    size: "Multiple-star system",

    mass:
        "Multiple-star system",

    temperature:
        "Varies by component",

    composition:
        "Hydrogen and helium",

    atmosphere:
        "Stellar plasma",

    rotation:
        "Varies",

    orbit:
        "Multiple-star system",

    textureStyle: "star",

    atmosphereColor: 0xffc66b,

    hasAtmosphere: true,

    facts: [
        "Alpha Centauri is the closest star system to the Solar System.",
        "It contains multiple stars.",
        "The system includes Alpha Centauri A, B and Proxima Centauri."
    ]
});


export const Betelgeuse = createBody({

    name: "Betelgeuse",
    type: "Star",

    position: [250, 100, -260],

    radius: 7,
    color: 0xff7045,

    size: "Red supergiant",

    mass:
        "Approximately 16–19 solar masses",

    temperature:
        "Approximately 3,500°C",

    composition:
        "Hydrogen, helium and heavier elements",

    atmosphere:
        "Extended stellar atmosphere",

    rotation:
        "Complex",

    orbit:
        "Milky Way",

    textureStyle: "redSupergiant",

    atmosphereColor: 0xff633d35,

    hasAtmosphere: true,

    facts: [
        "Betelgeuse is a red supergiant.",
        "It is vastly larger than the Sun.",
        "It is in an advanced stage of stellar evolution."
    ]
});


export const Vega = createBody({

    name: "Vega",
    type: "Star",

    position: [190, 80, -120],

    radius: 3,
    color: 0xbfdcff,

    size: "Approximately 2.4 million km",

    mass:
        "Approximately 2.1 solar masses",

    temperature:
        "Approximately 9,600°C",

    composition:
        "Hydrogen and helium",

    atmosphere:
        "Stellar plasma",

    rotation:
        "Rapid",

    orbit:
        "Milky Way",

    textureStyle: "blueWhiteStar",

    atmosphereColor: 0xb9d8ff,

    hasAtmosphere: true,

    facts: [
        "Vega is one of the brightest stars visible from Earth.",
        "It is a blue-white main-sequence star.",
        "Vega has been studied extensively by astronomers."
    ]
});


export const Rigel = createBody({

    name: "Rigel",
    type: "Star",

    position: [280, -100, -240],

    radius: 6,
    color: 0x9bc7ff,

    size: "Blue supergiant",

    mass:
        "Many times the mass of the Sun",

    temperature:
        "Extremely hot blue-white surface",

    composition:
        "Hydrogen and helium",

    atmosphere:
        "Stellar plasma",

    rotation:
        "Complex",

    orbit:
        "Milky Way",

    textureStyle: "blueSupergiant",

    atmosphereColor: 0x8fbaff,

    hasAtmosphere: true,

    facts: [
        "Rigel is a blue supergiant.",
        "It is one of the brightest stars in the Orion constellation."
    ]
});


/* =========================================================
   ARRAYS
========================================================= */

export const planetObjects = [
    Mercury,
    Venus,
    Earth,
    Mars,
    Jupiter,
    Saturn,
    Uranus,
    Neptune
];


export const dwarfPlanetObjects = [
    Pluto,
    Ceres,
    Eris,
    Haumea,
    Makemake
];


export const moonObjects = [
    Moon,

    Phobos,
    Deimos,

    Io,
    Europa,
    Ganymede,
    Callisto,

    Titan,
    Rhea,
    Enceladus,
    Mimas,
    Iapetus,

    Miranda,
    Ariel,
    Titania,
    Oberon,

    Triton,
    Nereid
];


export const starObjects = [
    Sun,
    Sirius,
    AlphaCentauri,
    Betelgeuse,
    Vega,
    Rigel
];


export const celestialObjects = [
    Sun,

    ...planetObjects,

    ...dwarfPlanetObjects,

    ...moonObjects,

    Sirius,
    AlphaCentauri,
    Betelgeuse,
    Vega,
    Rigel
];


/*
Remove accidental duplicates by name.
*/

export const allCelestialObjects =
    celestialObjects.filter(
        (object, index, array) =>
            array.findIndex(
                item =>
                    item.name === object.name
            ) === index
    );


/* =========================================================
   GET OBJECT
========================================================= */

export function getCelestialObject(name) {

    if (!name) {
        return null;
    }

    const normalized =
        String(name)
            .trim()
            .toLowerCase();

    return allCelestialObjects.find(
        object =>
            object.name
                .toLowerCase() === normalized
    ) || null;
}


/* =========================================================
   GET ALL
========================================================= */

export function getCelestialObjectList() {

    return [
        ...allCelestialObjects
    ];
}


/* =========================================================
   GET BY TYPE
========================================================= */

export function getObjectsByType(type) {

    if (!type) {
        return [];
    }

    const normalized =
        String(type)
            .trim()
            .toLowerCase();

    return allCelestialObjects.filter(
        object =>
            object.type
                .toLowerCase() === normalized
    );
}


/* =========================================================
   SEARCH
========================================================= */

export function searchCelestialObjects(query) {

    if (!query) {
        return [];
    }

    const normalized =
        String(query)
            .trim()
            .toLowerCase();

    return allCelestialObjects.filter(
        object =>
            object.name
                .toLowerCase()
                .includes(normalized)
    );
}


/* =========================================================
   DEFAULT EXPORT
========================================================= */

export default {

    Sun,

    planetObjects,

    dwarfPlanetObjects,

    moonObjects,

    starObjects,

    celestialObjects,

    allCelestialObjects,

    getCelestialObject,

    getCelestialObjectList,

    getObjectsByType,

    searchCelestialObjects
};
